# Generated by Django 3.1.5 on 2021-01-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('wechat', models.CharField(max_length=32)),
                ('qq', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=32)),
            ],
        ),
    ]
